add notebook and sample data
project-illusion/scrapper pull request #2
Opened 2020-12-05 12:13 UTC by M46F

2020-12-05 12:13 UTC, M46F commented
@carash plz review thx

2020-12-05 12:46 UTC, carash requested changes
Yey being a critic is fun

2020-12-05 12:46 UTC, carash commented on data/example/character/fischl.yml
> +  CRIT DMG: '50'
IMO storing stats should be stored in list with name and value
```suggestion
  Stats:
  - Name: Base HP
    Value : 770
  - Name: Base ATK
    Value : 20
  - Name: Base DEF
    Value : 50
  - Name: ATK%
    Value : 0
  - Name: Crit Rate
    Value : 5
  - Name: Crit Damage
    Value : 50
```

2020-12-05 12:46 UTC, carash commented on data/example/character/fischl.yml
> +    1-Hit DMG: 44.12%
imo % should not be stored

2020-12-05 12:46 UTC, carash commented on data/example/character/fischl.yml
> +  Base HP: '1979'
pls store as number

2020-12-05 12:47 UTC, M46F commented on data/example/character/fischl.yml
> +  CRIT DMG: '50'
would you mind providing example for this?

2020-12-05 12:48 UTC, M46F commented on data/example/character/fischl.yml
> +    1-Hit DMG: 44.12%
hmm, how to differentiate percentage and raw number then?

2020-12-05 12:48 UTC, M46F commented on data/example/character/fischl.yml
> +  Base HP: '1979'
males ✌️ 


gadeng, nnt w edit

2020-12-05 12:50 UTC, carash commented on data/example/character/fischl.yml
> +    1-Hit DMG: 44.12%
ah right, ok then

2020-12-05 12:52 UTC, M46F commented on data/example/character/fischl.yml
> +  CRIT DMG: '50'
ah ya w mabuk lol, okok

2020-12-05 12:53 UTC, carash commented on data/example/character/fischl.yml
> +  CRIT DMG: '50'
![image](https://user-images.githubusercontent.com/14951038/101243522-91912380-3733-11eb-90da-d482e8b067fa.png)

2020-12-06 06:37 UTC, M46F commented on data/example/character/fischl.yml
> +  Base HP: '1979'
updated om

2020-12-06 06:38 UTC, M46F commented on data/example/character/fischl.yml
> +  CRIT DMG: '50'
updated om

2020-12-27 07:08 UTC, carash approved these changes

2020-12-27 08:34 UTC, merged